language: node_js

os:
  - linux
  - osx

env:
  - TRAVIS_NODE_VERSION="6" ARCH="x64"
  - TRAVIS_NODE_VERSION="5" ARCH="x64"
  - TRAVIS_NODE_VERSION="4" ARCH="x64"
  - TRAVIS_NODE_VERSION="iojs" ARCH="x64"
  - TRAVIS_NODE_VERSION="0.12" ARCH="x64"
  - TRAVIS_NODE_VERSION="0.10" ARCH="x64"

  - TRAVIS_NODE_VERSION="6" ARCH="x86"
  - TRAVIS_NODE_VERSION="5" ARCH="x86"
  - TRAVIS_NODE_VERSION="4" ARCH="x86"
  - TRAVIS_NODE_VERSION="iojs" ARCH="x86"
  - TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - TRAVIS_NODE_VERSION="0.10" ARCH="x86"

matrix:
  exclude:
    - os: osx
      env: ARCH="x86"

before_install:
  - nvm install $TRAVIS_NODE_VERSION

  - PATH=$PATH:`pwd`/node_modules/.bin
  - BASE_URL=$(node -p "'https://nodejs.org/download/release/' + process.version")
  - X86_FILE=$(node -p "'node-' + process.version + '-' + process.platform + '-x86'")
  - if [[ "$ARCH" == "x86" ]]; then wget $BASE_URL/$X86_FILE.tar.gz; tar -xf $X86_FILE.tar.gz; export PATH=$X86_FILE/bin:$PATH; fi

  - if [[ "$ARCH" == "x86" ]]; then sudo apt-get -y install binutils:i386 gcc-4.8:i386 g++-4.8:i386 | true; fi
  - export CXX=g++-4.8;

addons:
  # addons required for compiling native node modules
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib

script:
  - npm install -g node-gyp
  - node-gyp rebuild
  - node --version
  - npm --version
  - npm test
