version: "{build}"

init:
  # Windows line endings.
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "3.3.1" # latest iojs
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

platform:
  - x86
  - x64

install:
  - git submodule update --init --recursive
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)

before_build:
  - npm install -g node-gyp

build_script:
  - node-gyp rebuild
  - npm install

test_script:
  # Output versions for reference.
  - node --version
  - npm --version

  - npm test
